services:
  - type: web
    name: llm-analysis-quiz
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EMAIL
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: HEADLESS
        value: True
      - key: QUIZ_TIMEOUT
        value: 170
      - key: BROWSER_TIMEOUT
        value: 30000
